- apps/platform/db/migrations/20230226042803_add_user_list_version.js
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/channels/text/TextJob.ts
- apps/platform/src/channels/text/TwilioTextProvider.ts
- apps/platform/src/lists/List.ts
- apps/platform/src/lists/ListPopulateJob.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/users/UserEventRepository.ts
- apps/ui/src/ui/Button.css
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/form/SelectField.css
- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/users/ListDetail.tsx
- apps/ui/src/views/users/RuleBuilder.tsx
- Moves to have lists regenerate every time rules change
- Fixes case where list would add all users right at list creation
- Fixes Twilio integration (has been tested now)
> Fix list generation and Twilio

- apps/platform/src/storage/ImageController.ts
- apps/platform/src/storage/ImageService.ts
- apps/ui/src/api.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Modal.tsx
- apps/ui/src/ui/form/UploadField.tsx
- apps/ui/src/views/campaign/EmailEditor.css
- apps/ui/src/views/campaign/EmailEditor.tsx
- apps/ui/src/views/campaign/ImageGalleryModal.css
- apps/ui/src/views/campaign/ImageGalleryModal.tsx
Also adds a grid view gallery to see previously uploaded images
Does not handle alt tags or deleting images currently
> Adds UI for uploading images for emails

- apps/platform/src/journey/JourneyRepository.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/ui/form/SelectField.css
- apps/ui/src/ui/form/SelectField.tsx
- apps/ui/src/ui/utils.tsx
- apps/ui/src/views/campaign/CampaignEditModal.tsx
- apps/ui/src/views/campaign/LocaleSelector.tsx
- apps/ui/src/views/users/RuleBuilder.tsx
- updated SelectField to be generic, separated react-hook-form bindings
- updated sidebar to use SelectField for project picker
- fixed journey creation transaction
> update sidebar to use select field, update select field api

- apps/platform/db/migrations/20230303141811_add_schedule_lock.js
- apps/platform/src/app.ts
- apps/platform/src/config/scheduler.ts
This will prevent everything in the scheduler from running N times (N being the number of servers that are running)
> Creates a system for locking scheduled jobs

- apps/platform/src/tags/TagController.ts
- apps/platform/src/tags/TagService.ts
- apps/ui/src/api.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/SearchTable.tsx
- apps/ui/src/ui/form/MultiSelect.tsx
- apps/ui/src/ui/utils.tsx
- apps/ui/src/views/campaign/CampaignEditModal.tsx
- apps/ui/src/views/journey/Journeys.tsx
- apps/ui/src/views/router.tsx
- apps/ui/src/views/settings/Subscriptions.tsx
- apps/ui/src/views/settings/TagPicker.tsx
- apps/ui/src/views/settings/Tags.tsx
- apps/ui/src/views/users/UserDetailSubscriptions.tsx
- adds a tag picker option to `SearchTable` (UI polishing in progress still)
- adds tag section in settings
- adds subscription creation form
- fixes auto-selection for select fields in campaigns
> adds tag and sub creation, tag filter to journeys

- apps/platform/package.json
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/config/database.ts
- apps/platform/src/core/Model.ts
- apps/platform/src/render/LinkService.ts
The image was not being embedded properly into the emails
> Fix email open tracking

- .vscode/settings.json
- apps/ui/package.json
- apps/ui/src/index.tsx
- apps/ui/src/ui/Button.css
- apps/ui/src/ui/Button.tsx
- apps/ui/src/ui/Menu.css
- apps/ui/src/ui/Menu.tsx
- apps/ui/src/ui/Modal.tsx
- apps/ui/src/ui/NavLink.tsx
- apps/ui/src/ui/Pagination.css
- apps/ui/src/ui/Pagination.tsx
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/ui/icons.tsx
- apps/ui/src/variables.css
- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/campaign/EmailEditor.tsx
- apps/ui/src/views/journey/Journeys.tsx
- apps/ui/src/views/router.tsx
- apps/ui/src/views/settings/ApiKeys.tsx
- apps/ui/src/views/settings/IntegrationModal.tsx
- apps/ui/src/views/settings/Integrations.tsx
- apps/ui/src/views/settings/Subscriptions.tsx
- apps/ui/src/views/settings/Tags.tsx
- apps/ui/src/views/settings/Teams.tsx
- apps/ui/src/views/users/ListDetail.tsx
- apps/ui/src/views/users/Lists.tsx
- apps/ui/src/views/users/RuleBuilder.tsx
Moves all icons to be stored SVGs as JSX. Is a combination of Bootstrap icons and Hero icons
> Updates icons

- apps/platform/package.json
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/config/database.ts
- apps/platform/src/core/validate.ts
- apps/platform/src/render/Template.ts
- apps/platform/src/render/TemplateController.ts
- apps/platform/src/render/TemplateService.ts
- apps/platform/src/utilities/index.ts
- apps/ui/src/api.ts
- apps/ui/src/contexts.ts
- apps/ui/src/ui/Preview.tsx
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/ui/utils.tsx
- apps/ui/src/views/campaign/CampaignDesign.tsx
- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/campaign/LaunchCampaign.tsx
- apps/ui/src/views/campaign/LocaleSelector.tsx
- apps/ui/src/views/campaign/TemplateDetail.tsx
- package-lock.json
- Fixes navigation after creating locale
- Fixes locale selector
- Allows for template fields to be empty
- Adds validation before campaign launch for template fields
- Refactors form validation
- Adds better error messaging for validation at large
> Cleans up lots of broken things around campaigns

- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/channels/ProviderService.ts
- apps/platform/src/channels/text/NexmoTextProvider.ts
- apps/platform/src/channels/text/PlivoTextProvider.ts
- apps/platform/src/channels/text/TwilioTextProvider.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/projects/ProjectService.ts
- Creates a subscription of each type when a project is created
- Fixes external IDs being filled in when creating a provider
> Fixes provider creation and project subscriptions

- apps/platform/src/client/SegmentController.ts
- docs/docs/providers/segment.md
Also adds some docs on how to use it
> Fixes Segment client URL

- .github/workflows/test.yml
- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/providers/email/EmailChannel.ts
- apps/platform/src/render/LinkService.ts
- apps/platform/src/render/Template.ts
- apps/platform/src/render/__spec__/LinkService.spec.ts
- apps/platform/src/render/__spec__/__snapshots__/LinkService.spec.ts.snap
- apps/platform/src/render/index.ts
- apps/ui/package-lock.json
- apps/ui/src/types.ts
- apps/ui/src/views/campaign/TemplateDetail.tsx
A "preheader" is the text that appears immediately following the subject line. The approach suggested by the internet is to use a span which is set to be largely invisible to include the text so that it is parsed out.
Also added some tests for click and open tracking
> Adds ability to inject a preheader into emails

- apps/platform/db/migrations/20230317133712_update_campaign_multiple_lists.js
- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/campaigns/CampaignController.ts
- apps/platform/src/campaigns/CampaignError.ts
- apps/platform/src/campaigns/CampaignGenerateListJob.ts
- apps/platform/src/campaigns/CampaignSendJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignStateJob.ts
- apps/platform/src/campaigns/CampaignTriggerJob.ts
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/config/scheduler.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/queue/Job.ts
- apps/platform/src/queue/MemoryQueueProvider.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Button.css
- apps/ui/src/ui/Button.tsx
- apps/ui/src/ui/DataTable.css
- apps/ui/src/ui/form/OptionField.tsx
- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/CampaignForm.tsx
- apps/ui/src/views/campaign/CampaignOverview.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/users/ListTable.tsx
- Fixes tons of bugs related to campaign sending
- Allows for send and exclusion lists
- Adds new UI for creating campaigns
- Fixes aborting campaigns
- Refactors campaign states and jobs
> Allows for send and exclusion lists + campaign improvements

- apps/ui/src/views/journey/JourneyEditor.css
Makes icon handles square and makes hover effect on sidebar items look nicer
> Minor cleanup to journey icon styling

- apps/platform/src/projects/ProjectApiKey.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/projects/ProjectService.ts
- apps/ui/package-lock.json
- apps/ui/package.json
- apps/ui/src/index.css
- apps/ui/src/ui/Button.css
- apps/ui/src/ui/Button.tsx
- apps/ui/src/ui/Heading.css
- apps/ui/src/ui/Menu.css
- apps/ui/src/ui/Modal.css
- apps/ui/src/ui/Modal.tsx
- apps/ui/src/ui/NavLink.tsx
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/views/settings/ApiKeys.tsx
- apps/ui/src/views/settings/Subscriptions.tsx
- Adds close button to modals (makes it more clear how to exit, especially when you have double modals)
- Fixes actions in API keys
- Cleans up headers and spacing (fixes weird movements when there are action buttons)
- Fixes extra spacing in nav buttons
- Allows for buttons to have extra params that come from HTML buttons 
- Makes form submit button only be the width of the button itself (instead of having label grow to entire width)
> UI Improvements

- .github/workflows/test.yml
- apps/platform/src/campaigns/CampaignSendJob.ts
- apps/platform/src/config/scheduler.ts
- apps/ui/src/ui/form/EntityIdPicker.tsx
- Fixes campaign issue when sending
- Another improvement to deadlocks
- Fixes issue with `disabled` param on combobox https://github.com/tailwindlabs/headlessui/issues/2327
- Adds build job to tests so we catch things earlier
> Minor bug fixes & build job

- apps/platform/db/migration.stub
- apps/platform/db/migrations/20221118223317_stored_token_rename.js
- apps/platform/db/migrations/20221210193723_add_tags.js
- apps/platform/db/migrations/20230120144724_add_journey_step_uuid.js
- apps/platform/db/migrations/20230204200316_step_type_x_y_float.js
- apps/platform/db/migrations/20230212215653_rename_journey_steps_uuid.js
- apps/platform/db/migrations/20230306220639_add_journey_step_child_priority.js
- apps/platform/db/migrations/20230319192319_add_project_roles.js
- apps/platform/scripts/create-migration.mjs
- apps/platform/src/config/database.ts
- apps/platform/src/config/scheduler.ts
- apps/platform/src/utilities/index.ts
- Improves test running
- Better error handling for failed tests
- Fixes issues around database not existing
- Moves to Typescript for migrations moving forward (with better stub)
> Migration cleanup

- apps/platform/db/migrations/20230326145047_drop_external_id_column.ts
- apps/platform/src/providers/Provider.ts
- apps/platform/src/providers/ProviderRepository.ts
- apps/platform/src/providers/ProviderService.ts
- apps/platform/src/providers/email/SESEmailProvider.ts
- apps/platform/src/providers/text/TwilioTextProvider.ts
- apps/ui/src/index.css
- apps/ui/src/types.ts
- apps/ui/src/ui/DataTable.css
- apps/ui/src/ui/Modal.css
- apps/ui/src/ui/form/TextField.tsx
- apps/ui/src/ui/icons.tsx
- apps/ui/src/views/auth/LoginBasic.tsx
- apps/ui/src/views/settings/ApiKeys.tsx
- apps/ui/src/views/settings/IntegrationModal.tsx
- apps/ui/src/views/settings/Integrations.tsx
- docs/docs/advanced/config.md
- docs/docs/providers/ses.md
- docs/src/css/custom.css
- Improves UI for provider detail screens (adding easy to find URLs for things in docs)
- Cleans up unneeded code
- Adds copy button for API keys
- Improved docs
> Provider cleanup

- apps/platform/src/app.ts
- apps/platform/src/config/env.ts
- apps/platform/src/config/logger.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/index.ts
- apps/platform/src/providers/LoggerProvider.ts
- apps/platform/src/providers/email/EmailProvider.ts
- apps/platform/src/queue/MemoryQueueProvider.ts
- apps/platform/src/queue/Queue.ts
- apps/platform/src/queue/QueueProvider.ts
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/queue/SQSQueueProvider.ts
- apps/platform/src/worker.ts
- docker-compose.yml
Allows for running either just API or just worker based on an environment variable
> Allows for running separate job queue from API

- apps/platform/db/migrations/20230331203356_improve_user_indexes.js
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/users/UserEventRepository.ts
- apps/ui/src/ui/SearchTable.tsx
- apps/ui/src/ui/Stack.css
- Increases batch size
- Improves indexes
> Misc Performance Improvements

- apps/platform/db/migration.stub
- apps/platform/db/migrations/20230401212338_add_user_locale_column.js
- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/client/Client.ts
- apps/platform/src/client/ClientController.ts
- apps/platform/src/client/SegmentController.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/users/User.ts
- apps/platform/src/users/UserController.ts
- apps/platform/src/utilities/index.ts
- apps/ui/src/views/users/UserDetailEvents.tsx
- apps/ui/src/views/users/Users.tsx
- Timezones & locales are now parsed in from Segment and can be provided in client libraries
- Templates look at partial locales
- Phone numbers are formatted
> Improves timezone and locale support

- apps/platform/src/client/Client.ts
- apps/platform/src/client/EventPostJob.ts
- apps/platform/src/client/SegmentController.ts
- apps/platform/src/queue/Job.ts
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/users/UserRepository.ts
- apps/ui/src/views/users/Users.tsx
- Adds retry logic and backoff for jobs that fail
- Improves the UI for the users table
- Fixes Segment importing the locale
> Improves users table UI & job retry logic

- apps/platform/src/client/SegmentController.ts
- apps/ui/package-lock.json
- apps/ui/package.json
- apps/ui/src/ui/DataTable.css
- apps/ui/src/views/users/Users.tsx
Also tweaks users table some more
> Segment locale parsing improvement

- apps/platform/db/migrations/20230403152432_add_admin_profile_image.js
- apps/platform/src/auth/Admin.ts
- apps/platform/src/auth/OpenIDAuthProvider.ts
- apps/ui/src/index.css
- apps/ui/src/types.ts
- apps/ui/src/ui/Button.tsx
- apps/ui/src/ui/DataTable.css
- apps/ui/src/ui/Menu.tsx
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/ui/icons.tsx
- apps/ui/src/views/campaign/CampaignDelivery.tsx
- apps/ui/src/views/settings/Teams.tsx
- apps/ui/src/views/users/UserDetailSubscriptions.tsx
- Makes sidebar adaptive so that at least most content can be viewed semi well on mobile (things like forms still suck though)
- Adds profile image for OpenID
- Minor other UI improvements
> Makes design less terrible on mobile

- apps/platform/src/client/SegmentController.ts
- Fixed Segment crash related to value not always being present
> Fixes Segment parsing crash

- apps/platform/db/migrations/20230407162219_add_campaign_stats.js
- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/campaigns/CampaignInteractJob.ts
- apps/platform/src/campaigns/CampaignSendJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignStateJob.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/config/scheduler.ts
- apps/platform/src/providers/email/EmailChannel.ts
- apps/platform/src/providers/email/SESEmailProvider.ts
- apps/platform/src/render/LinkService.ts
- apps/ui/docker/nginx/conf.d/default.conf
- apps/ui/src/types.ts
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/Tile.css
- apps/ui/src/ui/Tile.tsx
- apps/ui/src/views/auth/Auth.css
- apps/ui/src/views/campaign/CampaignDelivery.tsx
- Adds when an email was opened
- Adds total number of clicks per user
- Refactors how stats are generated
- Improves inbound bounces and complaints
- Improves responsive design of these elements
> Adds more campaign delivery stats

- .github/workflows/build.yml
- apps/platform/package.json
- apps/ui/package.json
Using `latest` causes all sorts of problems and we aren't tagging anything appropriately currently
> Tags docker build with release tag

- apps/platform/src/providers/email/MailgunEmailProvider.ts
- apps/platform/src/providers/email/SESEmailProvider.ts
- apps/platform/src/providers/push/LocalPushProvider.ts
- apps/platform/src/providers/push/PushChannel.ts
- apps/platform/src/providers/text/NexmoTextProvider.ts
- apps/platform/src/providers/text/PlivoTextProvider.ts
- apps/platform/src/providers/text/TwilioTextProvider.ts
- apps/platform/src/render/Template.ts
- apps/platform/src/render/TemplateService.ts
- apps/platform/src/subscriptions/SubscriptionController.ts
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/ui/form/SchemaFields.css
- apps/ui/src/ui/form/SchemaFields.tsx
- apps/ui/src/ui/form/SwitchField.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/campaign/TemplateDetail.tsx
- Fixes push notification provider
- Improves provider schema form building
> Provider Improvements

- apps/platform/src/projects/ProjectAdminController.ts
- apps/ui/src/ui/form/EntityIdPicker.tsx
- apps/ui/src/ui/form/MultiSelect.tsx
- apps/ui/src/ui/form/Select.css
- apps/ui/src/ui/form/SingleSelect.tsx
- docker-compose.yml
- docs/docs/overview/quick-start.md
Fixes animations related to dropdown pickers
> Dropdown pickers bug

- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/client/Client.ts
- apps/platform/src/client/ClientController.ts
- apps/platform/src/client/SegmentController.ts
- apps/platform/src/config/controllers.ts
- apps/platform/src/config/env.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/queue/Queue.ts
- apps/platform/src/queue/QueueProvider.ts
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/queue/SQSQueueProvider.ts
- apps/platform/src/users/UserAliasJob.ts
- apps/platform/src/users/UserRepository.ts
- apps/ui/package-lock.json
- apps/ui/package.json
- apps/ui/src/api.ts
- apps/ui/src/types.ts
- apps/ui/src/views/router.tsx
- apps/ui/src/views/settings/Performance.tsx
- apps/ui/src/views/settings/Settings.tsx
- docs/package-lock.json
- docs/package.json
- package-lock.json
- Adds performance monitoring for queues
- Moves aliasing to a job
- Allows for bulk processing of SQS queues
- Reverts SQS package back to official one
- Allows for TLS options to be set for Redis queue
> Improves Redis and SQS queues

- apps/platform/src/projects/ProjectService.ts
- apps/platform/src/providers/webhook/LocalWebhookProvider.ts
- apps/platform/src/render/TemplateController.ts
- apps/platform/src/render/TemplateService.ts
- apps/ui/src/contexts.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Preview.css
- apps/ui/src/ui/Preview.tsx
- apps/ui/src/ui/form/EntityIdPicker.tsx
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/ui/form/JsonField.tsx
- apps/ui/src/ui/form/MultiSelect.tsx
- apps/ui/src/ui/form/Select.css
- apps/ui/src/ui/form/SingleSelect.tsx
- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/campaign/CreateLocaleModal.tsx
- apps/ui/src/views/campaign/EditLocalesModal.tsx
- apps/ui/src/views/campaign/EmailEditor.tsx
- apps/ui/src/views/campaign/LocaleSelector.tsx
- apps/ui/src/views/campaign/TemplateDetail.tsx
- More fixes to dropdowns (ended up just removing transitions completely since different things kept breaking)
- Improves locale creation
> Adds UI for creating webhook type campaigns

- apps/ui/docker/nginx/conf.d/default.conf
For some paths we are looking to actually rewrite the path vs just pass it along to a proxy
> Fixes Nginx config

- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/projects/Project.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/providers/Provider.ts
- apps/platform/src/utilities/index.ts
Offsets were just from UTC, not a new date with the UTC time only
> Fixes offsets for campaign sends not matching user timezone

- apps/ui/src/views/campaign/CampaignDetail.tsx
Currently you can only cancelling a campaign that is currently running, not one that is scheduled for the future
> Allows for aborting scheduled campaigns

- apps/platform/src/campaigns/CampaignInteractJob.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Tile.tsx
- apps/ui/src/views/campaign/CampaignDelivery.tsx
- apps/ui/src/views/users/UserDetail.tsx
- apps/ui/src/views/users/UserDetailAttrs.tsx
- Improves users UI
- Ensures bounces are reported in campaign sends
> Improves UI for campaign delivery

- apps/platform/src/lists/ListService.ts
- apps/platform/src/users/UserImport.ts
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/views/auth/LoginBasic.tsx
- apps/ui/src/views/campaign/editor/EmailEditor.tsx
> Ensures that lists have an external ID during upload

- apps/platform/src/users/UserImport.ts
Chunks queue additions to lower amount of time spent waiting for things to be added to the queue
> Moves adding to the queue to chunks

- apps/platform/src/campaigns/CampaignInteractJob.ts
- apps/platform/src/campaigns/CampaignSendJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignStateJob.ts
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/lists/ProcessListsJob.ts
- apps/platform/src/providers/MessageTrigger.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/email/EmailJob.ts
- apps/platform/src/providers/email/MailgunEmailProvider.ts
- apps/platform/src/providers/email/SESEmailProvider.ts
- apps/platform/src/render/LinkController.ts
- apps/platform/src/render/LinkService.ts
- apps/platform/src/utilities/index.ts
- apps/ui/Dockerfile
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/ui/form/TextInput.tsx
- apps/ui/src/views/campaign/CampaignForm.tsx
- apps/ui/src/views/campaign/LaunchCampaign.tsx
- Improves send interactions
- Improves SES connector (correctly handles soft vs hard bounces). Soft bounces could just be out of office notifications, etc
- Throttled messages abort correctly. Previously they would still send
- Adds UI alert to double check that you actually want to send a scheduled message immediately
Completes PV-55
> Campaign sending improvements

- apps/platform/src/config/scheduler.ts
- apps/platform/src/utilities/index.ts
- docs/docs/clients/android.md
Fixes bug that would prevent state generation from running when value is NULL
> Fixes campaign state job

- apps/platform/jest.config.js
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/client/__tests__/ClientController.spec.ts
- apps/platform/src/projects/__tests__/ProjectTestHelpers.ts
- apps/platform/src/render/__tests__/LinkService.spec.ts
- apps/platform/src/subscriptions/SubscriptionService.ts
- apps/platform/src/users/UserRepository.ts
- apps/platform/src/users/__tests__/UserRepository.spec.ts
Also minor bug fixes and new test cases
> Fixes when a user will subscribe for push notifications

- apps/platform/src/lists/ListService.ts
- apps/ui/src/ui/DataTable.tsx
- apps/ui/src/views/users/ListDetail.tsx
- Enables sorting of the users that have joined a list
- Also adds the ability to provide a custom sort key when sorting
> Adds sorting to user list on lists detail page

- apps/ui/package-lock.json
- apps/ui/package.json
- apps/ui/src/utils.ts
- apps/ui/src/views/campaign/CampaignOverview.tsx
- apps/ui/src/views/campaign/LaunchCampaign.tsx
Fixes bug related to launching a campaign if you are in a timezone other than that of the project itself
> Updates campaign launch to be project timezone specific

- apps/platform/src/journey/JourneyStep.ts
- package-lock.json
- adds same basic check before enqueuing action step campaign, marks as failed if required info is not present.
- marks step as failed if invalid campaign ID (probably don't want to continue if this is the case)
> Adds similar email and phone check before journey action sends campaign

- apps/platform/src/app.ts
- apps/platform/src/config/database.ts
- apps/platform/src/config/env.ts
- apps/platform/src/core/Model.ts
- apps/platform/src/index.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/push/PushJob.ts
- apps/platform/src/users/UserController.ts
- apps/platform/src/users/UserRepository.ts
- apps/ui/src/ui/JsonPreview.css
- apps/ui/src/ui/JsonPreview.tsx
- Fixes UI related to JSON viewer
- Fixes UI for sorting different areas
- Adds better logging
> Minor code cleanup and improvements

- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/client/EventPostJob.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/analytics/Analytics.ts
- apps/platform/src/providers/analytics/SegmentProvider.ts
- apps/platform/src/providers/email/EmailJob.ts
- apps/platform/src/providers/push/PushJob.ts
- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/providers/webhook/WebhookJob.ts
- apps/platform/src/render/LinkService.ts
- apps/ui/src/ui/form/SchemaFields.tsx
- apps/ui/src/views/settings/IntegrationModal.tsx
- Fixes events not forwarding to analytics for link events
- Improves naming for events
- Allows for different conventions for analytic events
> Improves event naming & fixes analytic events

- apps/platform/src/queue/Queue.ts
- apps/platform/src/users/UserError.ts
- apps/platform/src/users/UserPatchJob.ts
- apps/platform/src/users/UserRepository.ts
- Allows for anonymous ID to be reset if no previous value exists
- Allows for jobs to error out so they appropriately retry
> Fixes job error handling so jobs retry

- apps/ui/src/contexts.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Menu.css
- apps/ui/src/ui/Menu.tsx
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/ui/icons.tsx
- apps/ui/src/views/organization/Admins.tsx
- apps/ui/src/views/organization/Performance.tsx
- apps/ui/src/views/project/ProjectSidebar.tsx
- apps/ui/src/views/router.tsx
- apps/ui/src/views/settings/Settings.tsx
- Introduces a separate section for viewing an organization's UI
- Allows for viewing all admins inside of an organization
- Moves performance to be under the organization section
> Adds base organization UI

- .github/workflows/publish.yml
- .github/workflows/test.yml
- apps/platform/Dockerfile
- apps/platform/nodemon.json
- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/api.ts
- apps/platform/src/app.ts
- apps/platform/src/boot.ts
- apps/platform/src/config/controllers.ts
- apps/platform/src/config/database.ts
- apps/platform/src/config/env.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/core/validate.ts
- apps/platform/src/index.ts
- apps/platform/src/providers/Provider.ts
- apps/platform/src/worker.ts
- apps/ui/package-lock.json
- apps/ui/package.json
- package-lock.json
- package.json
- tsconfig.base.json
- Adds Parcelvoy as a package
- Cleans up some things related to image deployment
- Improves how routes and jobs are registered
> Update release process

- apps/ui/src/views/journey/JourneyEditor.tsx
Fixes issue where journey save button would lock up if a save would fail preventing a re-save
> Fixes journey save button

- apps/platform/src/config/database.ts
- docker-compose.yml
- Adds a catch block around potential race condition
- Moves database health check to be more platform agnostic Moves init for worker to be dependent on api starting
> Fixes first boot race condition for database creation

- apps/platform/db/migrations/20230624135258_project_sms_opt_out.js
- apps/platform/src/core/Model.ts
- apps/platform/src/projects/Project.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/text/TextChannel.ts
- apps/platform/src/providers/text/__tests__/TextChannel.spec.ts
- apps/platform/src/render/index.ts
- apps/ui/src/types.ts
- apps/ui/src/views/project/ProjectForm.tsx
Adds ability to add unsubscribe instructions to the first SMS a user receives to comply with carrier requirements
> Adds SMS unsubscribe instructions

- apps/platform/src/projects/ProjectAdminRepository.ts
- apps/ui/src/views/settings/Teams.tsx
Its not appropriately using the combination ID
> Fixes switching an admins role

- apps/ui/src/views/campaign/CampaignDelivery.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- Fixes totals showing NaN
- Fixes verbiage
> Minor fixes to campaign screens

- apps/platform/src/config/database.ts
After initializing the database, the migration config wouldn't have the proper database selected
> Fixes issue with config not properly containing database

- apps/platform/src/config/database.ts
- docker-compose.yml
- Moves Docker Compose dependency health check
> Adds migration retry loops

- apps/platform/db/migrations/20230626205637_add_user_event_index.js
- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/email/EmailJob.ts
- apps/platform/src/providers/push/PushJob.ts
- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/queue/Queue.ts
- apps/ui/src/types.ts
- apps/ui/src/views/campaign/CampaignDelivery.tsx
- Adds lock state for messages
- Adds index to improve performance
- Small refactor
> Send reliability improvements

- apps/ui/src/ui/icons.tsx
- apps/ui/src/views/journey/JourneyEditor.css
- apps/ui/src/views/journey/JourneyEditor.tsx
- Adds waiting and completion stats to journeys
> Adds stats UI to journeys

- apps/platform/src/app.ts
- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/campaigns/CampaignSendJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
- apps/platform/src/config/rateLimit.ts
- apps/platform/src/config/scheduler.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/email/EmailJob.ts
- apps/platform/src/providers/push/PushJob.ts
- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/providers/webhook/WebhookJob.ts
- apps/platform/src/utilities/index.ts
- apps/ui/src/types.ts
- apps/ui/src/views/campaign/CampaignDelivery.tsx
- Moves rate limiter to use a sliding window vs fixed frame to hopefully reduce spiking
- Switches locks to use Redis instead of database
- Moves send jobs to use new locking system instead of database update
- Refactors chunking to use a shared wrapper
- Improves performance of campaign send job by batching redis job queuing
> Performance and locking improvements

- apps/platform/src/config/env.ts
- apps/platform/src/providers/email/SESEmailProvider.ts
- apps/platform/src/providers/text/TextChannel.ts
- apps/platform/src/providers/text/TwilioTextProvider.ts
- apps/platform/src/render/TemplateService.ts
- apps/ui/src/ui/Preview.tsx
- apps/ui/src/views/campaign/TemplateDetail.tsx
- docs/docs/providers/twilio.md
- Fixes provider urls
- Allows for proofing text messages
- Fixes opt out message previewing
> Fixes text preview and proofing

- apps/platform/src/providers/webhook/WebhookChannel.ts
> Fixes webhooks not building when body or headers are null

- apps/platform/src/rules/DateRule.ts
- apps/platform/src/rules/RuleHelpers.ts
- apps/ui/src/views/users/RuleBuilder.tsx
- Fixes event properties not properly filtering because the UI set them to be of type user
- Ensures that the initial list generation SQL query runs correctly for dates
> Fixes initial evaluation of dates

- apps/platform/src/render/TemplateService.ts
- apps/ui/src/views/campaign/CampaignDetail.tsx
Also adds a check to ensure you dont get multiple locales for a given campaign
> Allows for changing editor type for different locales

- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/render/Helpers/Date.ts
- apps/platform/src/users/UserEvent.ts
- apps/ui/src/views/journey/steps/Delay.tsx
- docs/docs/how-to/campaigns/templates.md
- Lets you switch between different date manipulation modes
- Adds more methods for date manipulation
> Adds additional options for delaying journeys

- apps/platform/src/config/rateLimit.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/text/TextChannel.ts
- apps/platform/src/providers/text/TextJob.ts
- Moves SMS to rate limit based on segments vs sends
> Allows for rate limiting to be more than one point

- apps/ui/package-lock.json
- apps/ui/package.json
- package.json
- Fixes build error related to Monaco types not being present. Related to package using Monaco as a peer dependency
> Explicitly adds Monaco editor

- apps/ui/package.json
Fixes [bug](https://github.com/calvinmetcalf/copyfiles/issues/59) related to `copyfiles` not appropriately copying css and assets from all folders
> Fixes `copyfiles` bug

- apps/ui/package.json
- apps/ui/tsconfig.lib.json
Adds fixes to NPM package building
> Additional build process tweaks

- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/providers/ProviderService.ts
- apps/ui/src/App.tsx
- apps/ui/src/index.css
- apps/ui/src/mod.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/PageContent.tsx
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/views/campaign/CampaignForm.tsx
- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/project/ProjectForm.tsx
- apps/ui/src/views/router.tsx
- Improves typing
- Adds notification if you don't have an integration setup
> Onboarding improvements

- apps/platform/db/migrations/20230814014024_add_locales.js
- apps/platform/src/config/controllers.ts
- apps/platform/src/projects/Locale.ts
- apps/platform/src/projects/ProjectLocaleController.ts
- apps/platform/src/projects/ProjectService.ts
- apps/ui/src/api.ts
- apps/ui/src/index.css
- apps/ui/src/types.ts
- apps/ui/src/ui/Button.css
- apps/ui/src/ui/Button.tsx
- apps/ui/src/ui/Sidebar.css
- apps/ui/src/views/campaign/LocaleEditModal.tsx
- apps/ui/src/views/campaign/LocaleSelector.tsx
- apps/ui/src/views/campaign/TemplateCreateModal.tsx
- apps/ui/src/views/router.tsx
- apps/ui/src/views/settings/Locales.tsx
- apps/ui/src/views/settings/Settings.tsx
Moves locales to be under the project instead of having to be entered for every template. Should help with non-technical folks entering the wrong thing in that field.
> Adds project based locales

- apps/ui/src/ui/Alert.tsx
- apps/ui/src/views/ErrorPage.css
- apps/ui/src/views/ErrorPage.tsx
- apps/ui/src/views/auth/Onboarding.tsx
- apps/ui/src/views/auth/OnboardingProject.tsx
- apps/ui/src/views/auth/OnboardingStart.tsx
- apps/ui/src/views/router.tsx
- Fixes 404 errors
- Tweaks to some styles
> Improves error messaging

- apps/platform/src/api.ts
- apps/platform/src/auth/AuthController.ts
- apps/platform/src/auth/AuthProvider.ts
- apps/platform/src/auth/OpenIDAuthProvider.ts
- apps/platform/src/auth/SAMLAuthProvider.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/organizations/OrganizationMiddleware.ts
- apps/platform/src/organizations/OrganizationService.ts
- Removes broad domain linking
- Improves cookie security
- Cleans up middleware for determining the organization
> Improves how auth links a user to an org

- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/app.ts
- apps/platform/src/boot.ts
- apps/platform/src/config/queue.ts
- apps/platform/src/config/stats.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/queue/Queue.ts
- apps/platform/tests/setup.ts
- apps/ui/src/api.ts
- apps/ui/src/views/organization/Performance.tsx
- Adds statistics wrapper to track usage
- Includes statistics in job queue
- Adds UI for tracking individual job queuing over time
> Adds better performance insights for jobs

- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/providers/ProviderRepository.ts
- apps/platform/src/providers/analytics/PosthogProvider.ts
- apps/platform/src/providers/analytics/index.ts
- docs/docs/overview/quick-start.md
- Also adds a way to change what the default provider is for analytics
> Add PostHog Provider

- apps/platform/src/providers/text/NexmoTextProvider.ts
- apps/platform/src/providers/text/PlivoTextProvider.ts
- apps/platform/src/providers/text/TextChannel.ts
- apps/platform/src/providers/text/TextError.ts
- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/providers/text/TwilioTextProvider.ts
- apps/platform/src/users/UserController.ts
- apps/ui/src/views/project/ProjectSidebar.tsx
- Ensures campaign status is updated on failure
- Catches common scenarios and handles appropriately
> Improves SMS error handling for common scenarios

- apps/platform/src/auth/Admin.ts
- apps/platform/src/auth/AuthProvider.ts
- apps/platform/src/auth/BasicAuthProvider.ts
- apps/platform/src/auth/OpenIDAuthProvider.ts
- apps/platform/src/auth/SAMLAuthProvider.ts
- apps/platform/src/error/SentryProvider.ts
- Improves account matching
- Prevents failed org setups from impeding sign in
> Improves auth flow

- apps/platform/src/config/env.ts
- apps/platform/src/queue/RedisQueueProvider.ts
Allows for setting a custom queue concurrency value so it can be adjusted based on load
> Moves queue concurrency to parameter

- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/TemplateCreateModal.tsx
- Fixes endless loop related to locales
- Fixes being able to select visual editor for emails
> Minor fixes to templates and locales

- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/editor/EmailEditor.css
- apps/ui/src/views/campaign/editor/EmailEditor.tsx
- apps/ui/src/views/campaign/editor/HtmlEditor.tsx
- Fixes cases where switching a locale and then entering an editor would revert back to the first available locale
- Improves UI for code editor
> Improves handling of locale during navigation

- README.md
- apps/platform/src/api.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/Modal.css
- apps/ui/src/ui/Tag.css
- apps/ui/src/ui/Tag.tsx
- apps/ui/src/views/journey/JourneyEditor.tsx
- apps/ui/src/views/settings/ApiKeys.tsx
- apps/ui/src/views/settings/Subscriptions.tsx
- apps/ui/src/views/settings/Tags.tsx
- apps/ui/src/views/users/UserDetailEvents.tsx
- Improves 404 error messaging
- Cleans up non titled columns
- Fixes event code view in dark mode
- Cleans up dates
- Fixes positioning of modals
> Various UI improvements

- apps/platform/src/subscriptions/SubscriptionController.ts
- apps/ui/src/setupProxy.js
- docs/docusaurus.config.js
- docs/src/css/custom.css
Adds Algolia search to documentation site
> Adds search to documentation

- apps/platform/src/projects/Project.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/projects/ProjectService.ts
- apps/platform/src/projects/__tests__/ProjectTestHelpers.ts
- apps/platform/src/providers/text/__tests__/TextChannel.spec.ts
- apps/platform/src/render/__tests__/LinkService.spec.ts
- apps/ui/src/ui/form/TextInput.css
- apps/ui/src/ui/form/TextInput.tsx
- apps/ui/src/utils.ts
- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/journey/JourneyEditor.css
- apps/ui/src/views/journey/JourneyEditor.tsx
- apps/ui/src/views/project/ProjectForm.tsx
- apps/ui/src/views/project/Projects.tsx
- apps/ui/src/views/settings/Locales.tsx
- Initial locale creation improvements
- Journey style tweaks
- Project creation ui improvements
> Improves project creation flow

- apps/platform/src/client/EventPostJob.ts
- apps/platform/src/journey/JourneyService.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/journey/__tests__/JourneyService.spec.ts
- apps/platform/src/lists/ListPopulateJob.ts
- apps/platform/src/lists/ListService.ts
- apps/ui/package-lock.json
- apps/ui/package.json
- apps/ui/src/ui/DataTable.tsx
- apps/ui/src/ui/PreviewImage.css
- apps/ui/src/views/journey/EntranceDetails.tsx
- apps/ui/src/views/journey/JourneyEditor.tsx
- apps/ui/src/views/journey/steps/Entrance.tsx
- apps/ui/src/views/journey/steps/Gate.tsx
- apps/ui/src/views/settings/Tags.tsx
- apps/ui/src/views/users/RuleBuilder.tsx
- package-lock.json
- event-based triggers for journeys
> Journey entrances via events

- apps/platform/db/migrations/20231013201848_add_rule_table.js
- apps/platform/src/client/EventPostJob.ts
- apps/platform/src/journey/JourneyService.ts
- apps/platform/src/lists/List.ts
- apps/platform/src/lists/ListController.ts
- apps/platform/src/lists/ListPopulateJob.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/lists/ListStatsJob.ts
- apps/platform/src/lists/__tests__/ListService.spec.ts
- apps/platform/src/render/TemplateService.ts
- apps/platform/src/rules/Rule.ts
- apps/platform/src/rules/RuleEngine.ts
- apps/platform/src/rules/RuleHelpers.ts
- apps/platform/src/rules/RuleService.ts
- apps/platform/src/rules/WrapperRule.ts
- apps/platform/src/rules/__tests__/RuleService.spec.ts
- apps/platform/src/users/UserPatchJob.ts
- apps/platform/src/users/UserRepository.ts
- apps/ui/src/types.ts
- apps/ui/src/views/journey/steps/Entrance.tsx
- apps/ui/src/views/settings/Subscriptions.tsx
- apps/ui/src/views/users/ListDetail.tsx
- apps/ui/src/views/users/RuleBuilder.tsx
- Moves to cache components of rules for faster evaluation
- Reworks how lists are generated
- Code cleanup and improvements
> Improved rule evaluation

- apps/platform/db/migrations/20231013222057_add_journey_user_step_ref_index.js
- apps/platform/package.json
- apps/platform/src/config/queue.ts
- apps/platform/src/config/scheduler.ts
- apps/platform/src/journey/JourneyRepository.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/journey/ScheduledEntranceJob.ts
- apps/platform/src/journey/ScheduledEntranceOrchestratorJob.ts
- apps/platform/src/journey/__tests__/JourneyService.spec.ts
- apps/platform/src/journey/__tests__/ScheduledEntranceJob.spec.ts
- apps/platform/src/utilities/index.ts
- apps/ui/package.json
- apps/ui/src/index.css
- apps/ui/src/ui/RRuleEditor.tsx
- apps/ui/src/ui/form/MultiOptionField.tsx
- apps/ui/src/ui/form/OptionField.css
- apps/ui/src/ui/form/ToggleButtonGroupInput.tsx
- apps/ui/src/views/journey/JourneyEditor.css
- apps/ui/src/views/journey/JourneyEditor.tsx
- apps/ui/src/views/journey/steps/Entrance.tsx
- docs/docs/how-to/journeys/_category_.json
- docs/docs/how-to/journeys/create.md
- docs/docs/how-to/journeys/index.md
- docs/docs/how-to/lists.md
- docs/docs/how-to/settings/_category_.json
- package-lock.json
- adds scheduler entrance type
- adds rrule editor component
- journey editor UI changes
WIP - needs additional testing
> Journeys - Scheduler-based Entrances

- apps/platform/package-lock.json
- apps/platform/src/lists/ListService.ts
- apps/ui/package-lock.json
- Adds check for `deleted_at` before evaluating lists
> Fixes soft deleted lists from still evaluating

- apps/platform/db/migrations/20231013201848_add_rule_table.js
Backports an in-code migration to create database rules from a lists embedded rules
> Adds data migration to list rules

- apps/ui/src/views/users/RuleBuilder.tsx
Fixes issue where rules where being added as parents and not filtering properly
> Fixes adding a new user rule

- apps/platform/db/migrations/20231013201848_add_rule_table.js
- apps/platform/src/rules/RuleService.ts
- Fixes root rule not being able to be changed
- Fixes cascading index
> Allows for updating root list rule

- apps/platform/src/auth/AuthProvider.ts
- Fixes issue related to OAuth users with verified domain attribute not saving properly
> Fixes Google OAuth

- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/campaigns/CampaignGenerateListJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignStateJob.ts
- Ensures sends start immediately
- Generates lists to send to immediately
> Improves speed of which sends start to enqueue

- apps/ui/src/ui/PreferencesContext.tsx
- make dark mode stick (completes PV-85)
> Make dark mode stay when you pick it specifically

- apps/platform/src/render/Template.ts
- apps/ui/src/ui/JsonPreview.tsx
- apps/ui/src/ui/Preview.tsx
- fixed webhook template preview to use correct color theming
- added null check when rendering webhook template components
> fixed webhook preview color scheme and template rendering errors

- apps/ui/package.json
- package-lock.json
- 11.9.3 reactflow had a bug that didn't allow connections between handles on drag/click
> upgrades reactflow version

- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/users/UserImport.ts
- apps/ui/package-lock.json
- Improves queue batching
- Improves import chunking
> Minor adjustments to queue

- apps/ui/src/index.css
- apps/ui/src/ui/Columns.css
- apps/ui/src/ui/Columns.tsx
- apps/ui/src/ui/Heading.css
- apps/ui/src/ui/Iframe.tsx
- apps/ui/src/ui/PageContent.tsx
- apps/ui/src/ui/Preview.css
- apps/ui/src/ui/SourceEditor.tsx
- apps/ui/src/ui/Tabs.css
- apps/ui/src/views/campaign/CampaignDetail.tsx
- apps/ui/src/views/campaign/CampaignPreview.css
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/campaign/TemplateDetail.tsx
- apps/ui/src/views/journey/steps/Event.tsx
- apps/ui/src/views/journey/steps/Update.tsx
- Brings all editors inline to use custom class
- Adjusts sizing of editors and preview windows to reduce double scrollbars
- Where possible expands the size of editors and preview windows to fill the entire viewport
> Improves sizing of preview and editors

- apps/platform/src/users/User.ts
Fixes having not all available rule paths always available for rule evaluation.
Also related to #316
> Adds missing rule paths to flattened user

- apps/platform/src/users/User.ts
- apps/platform/src/users/UserImport.ts
- docs/docs/how-to/lists.md
Fixes issue preventing CSV uploads from importing to a list when using the batch method.
Fixes #317
> Fixes user upload batching

- apps/ui/src/views/users/UserDetail.tsx
Adds a UI for removing a users data directly from the admin UI. This does not prevent the future capture of data, only purges existing data.
Referenced in #315
> Allows deleting a user from admin UI

- apps/platform/package-lock.json
- apps/platform/package.json
- apps/platform/src/app.ts
- apps/platform/src/campaigns/CampaignController.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/core/Model.ts
- apps/platform/src/journey/JourneyController.ts
- apps/platform/src/journey/JourneyRepository.ts
- apps/platform/src/lists/ListController.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/projects/ProjectService.ts
- apps/platform/src/render/TemplateService.ts
- apps/platform/src/users/UserDeleteJob.ts
- package-lock.json
- Adds an event emitter that triggers for different model events
- Adds soft delete archive method
- Brings usage of model methods inline with expected behavior
> Adds model event emitters

- apps/ui/src/ui/Button.css
- apps/ui/src/ui/form/EntityIdPicker.tsx
- apps/ui/src/ui/form/TextInput.css
- apps/ui/src/views/campaign/LocaleEditModal.tsx
- Fixes instructions for locales
- Improves disabled button style
> Adjusts button style and locale wording

- apps/platform/src/config/env.ts
- apps/platform/src/render/Template.ts
- apps/platform/src/utilities/index.ts
- apps/ui/src/views/campaign/CampaignPreview.tsx
- Shows errors in UI related to proof failing
- Adds validation to webhook templates
- Adds validation check for default `BASE_URL` value
> Improves error messaging for proofing templates

- apps/ui/src/types.ts
- apps/ui/src/views/journey/JourneyEditor.tsx
Fixes the data key field not saving for some field types and should address #344
> Fixes data key not saving for entrances

- docker/Dockerfile.render
Updates Render Dockerfile to use the latest entry points
> Updates Render docker file

- apps/platform/src/providers/text/HttpSMSProvider.ts
- apps/platform/src/providers/text/index.ts
> Adds base implementation of httpSMS text provider

- README.md
- apps/platform/Dockerfile
- docker/Dockerfile.render
- render.yaml
- Removes unneeded step from Dockerfile
- Sets default port for Render
- Fixes wrong folder for Render deployments
> Improvements to deployment/Render

- README.md
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/__tests__/CampaignService.spec.ts
> Switches to using list IDs when calculating estimated size

- apps/platform/src/auth/AdminController.ts
- apps/platform/src/auth/AdminRepository.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/projects/ProjectService.ts
Only show users who can access a project when searching for users to add
> Fixes access when adding to a project

- apps/platform/src/error/BugSnagProvider.ts
- apps/platform/src/error/SentryProvider.ts
Adds user to the logged error to help in debugging
> Add user to error logging

- apps/platform/src/auth/AdminController.ts
- apps/platform/src/auth/AdminRepository.ts
- apps/platform/src/core/Model.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/organizations/OrganizationService.ts
- apps/ui/src/api.ts
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/views/ErrorPage.tsx
- apps/ui/src/views/organization/Admins.tsx
- apps/ui/src/views/organization/Settings.tsx
- apps/ui/src/views/project/ProjectSidebar.tsx
- Improves UI for organizations
- Fixes bugs related to admins
- Allows for deleting an org
> Improves UI for organizations

- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/providers/email/EmailChannel.ts
- apps/platform/src/providers/email/EmailJob.ts
- apps/platform/src/providers/push/PushChannel.ts
- apps/platform/src/providers/push/PushJob.ts
- apps/platform/src/providers/text/TextChannel.ts
- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/providers/webhook/WebhookChannel.ts
- apps/platform/src/providers/webhook/WebhookJob.ts
- apps/platform/src/users/UserEventRepository.ts
- apps/ui/src/ui/Iframe.tsx
- apps/ui/src/views/users/UserDetailEvents.tsx
Cleans up senders and adds result to the events that are created
> Adds result of a send to the event

- apps/platform/db/migrations/20240310020733_add_admin_organization_role.js
- apps/platform/src/auth/Admin.ts
- apps/platform/src/auth/AuthMiddleware.ts
- apps/platform/src/auth/TokenRepository.ts
- apps/platform/src/organizations/Organization.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/organizations/OrganizationService.ts
- apps/platform/src/projects/ProjectController.ts
- apps/platform/src/projects/ProjectService.ts
- apps/ui/src/types.ts
- apps/ui/src/ui/form/FormWrapper.tsx
- apps/ui/src/views/organization/Settings.tsx
- adds `admins.role` column (member, admin, owner)
- enforce permissions at controller level
> Adds org role to admin, validate access for org features

- apps/platform/src/auth/Auth.ts
- apps/platform/src/auth/AuthMiddleware.ts
- apps/platform/src/auth/EmailAuthProvider.ts
- apps/platform/src/config/env.ts
- apps/platform/src/providers/email/SMPTEmailProvider.ts
- apps/ui/src/api.ts
- apps/ui/src/ui/Sidebar.tsx
- apps/ui/src/views/auth/Login.tsx
- Adds SMTP sender to support magic link auth
> Allows for authentication via magic links

- apps/ui/src/views/project/Projects.tsx
- apps/ui/src/views/router.tsx
> Fixes redirection for new installs

- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/users/UserRepository.ts
- Adds failed events for campaign sends
- Adds event when a user is created
Resolves #392
> Add additional internal events

- apps/platform/src/auth/Admin.ts
- apps/platform/src/auth/AdminController.ts
- apps/platform/src/organizations/Organization.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/organizations/OrganizationService.ts
- apps/platform/src/projects/ProjectAdminController.ts
- apps/ui/public/locales/en.json
- apps/ui/src/api.ts
- apps/ui/src/types.ts
- apps/ui/src/utils.ts
- apps/ui/src/views/organization/Admins.tsx
- apps/ui/src/views/organization/Organization.tsx
- apps/ui/src/views/router.tsx
- Adds ability to create admins directly from the UI
- Improves role security at the organization level
- Allows for changing other users roles
- Allows for removing admins
> Improve organization admin management

- apps/platform/src/campaigns/CampaignGenerateListJob.ts
- apps/platform/src/campaigns/ProcessCampaignsJob.ts
- apps/ui/src/views/campaign/CampaignForm.tsx
- Fixes regression related to being able to edit lists in a duplicated campaign
- Fixes bug where pending deleted campaigns would continue to try and process but fail
> Fixes editing campaign lists and scheduling deleted campaigns

- apps/platform/src/projects/ProjectService.ts
Ensures archived keys are hidden from the UI
Fixes #421
> Fixes archived API keys still showing

- apps/platform/src/campaigns/CampaignTriggerSendJob.ts
- apps/platform/src/journey/Journey.ts
- apps/platform/src/journey/JourneyController.ts
- apps/platform/src/journey/JourneyProcessJob.ts
- apps/platform/src/journey/JourneyService.ts
- apps/platform/src/journey/JourneyState.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/journey/__tests__/JourneyService.spec.ts
- apps/platform/src/journey/__tests__/JourneyStep.spec.ts
- Adds what type of trigger it was to the name, adds additional parameters to the event
- Slight refactor of journey code for cleanliness
Fixes #418
> Add type of trigger to event name

- apps/ui/src/views/campaign/Campaigns.tsx
- apps/ui/src/views/users/ListTable.tsx
> Fixes React hooks error related to i18n in tags

- apps/platform/src/users/UserRepository.ts
> Moves user created event to be able to trigger journeys and lists

- apps/platform/src/providers/MessageTriggerService.ts
- apps/ui/public/locales/en.json
- apps/ui/public/locales/es.json
- apps/ui/src/views/campaign/TemplateDetail.tsx
- Adds alert tags to template designer to show what is missing
- Properly calls out the true error in job failures when they are related to validation
Fixes #432
> Improves UI around missing campaign params

- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignTriggerSendJob.ts
- apps/platform/src/client/EventPostJob.ts
- apps/platform/src/journey/JourneyState.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/providers/MessageTriggerService.ts
- apps/platform/src/subscriptions/SubscriptionService.ts
Fixes loophole where a user could be sent a message through a journey even if they had unsubscribed from the given channel.
> Doesn't send a journey action if unsubscribed

- apps/ui/src/views/campaign/CampaignDelivery.tsx
- apps/ui/src/views/users/UserDetailSubscriptions.tsx
- Fixes clicking next in campaign delivery table
- Fixes i18n label when unsubscribing a user
> Minor i18n and render fixes

- apps/platform/src/providers/email/EmailChannel.ts
- docker-compose.yml
- Reduces amount of data stored by emails
- Bumps MySQL version to address sorting issues
> Minor performance tweaks

- apps/ui/src/ui/Iframe.tsx
More details from related issues people have had: https://github.com/facebook/react/issues/22847
Fixes #453
> Fixes issue related to Firefox clearing iFrames after load

- apps/platform/src/journey/JourneyStep.ts
> Trigger internal events on journey user updates and event creation

- apps/platform/src/providers/push/LocalPushProvider.ts
- package-lock.json
Fixes incorrect keys when entering in service token and properly replaces new lines
- Fixes #474 
- Fixes #475
> Fixes incorrect keys for new push notification package

- docs/docs/advanced/storage.md
- docs/docs/deploy/aws-ec2.md
Add additional details about what each env variable does for storage methods
> Improves docs for storage

- apps/platform/src/organizations/OrganizationMiddleware.ts
- apps/platform/src/render/LinkController.ts
- Add a cache around the universal link URL forwarding to improve performance
- Better handle single org installs when fetching the urls
> Improve universal link referencing and performance

- apps/platform/src/journey/JourneyRepository.ts
Only change the `next_scheduled_at` value when the schedule actually changes.
Fixes #506
> Fixes journey next scheduled date reset

- apps/platform/src/users/UserImport.ts
During list import its possible for numbers to get imported in a format that cant be sent to
> Force phone number format during list import

- apps/ui/src/views/campaign/Campaigns.tsx
> add open rate and click rate to campaign list

- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/providers/MessageTriggerService.ts
Modifications to https://github.com/parcelvoy/platform/pull/536 to have it properly handle all send situations and remove a job from being processed
> Check for unsubscribe state right before any send

- docs/docs/api/admin.md
- docs/docs/api/client.md
Been spending a little time before realising I was missing this in my curls 🤓
> Updated api docs urls with missing /api/

- docker-compose.yml
`platform` key needed to be specified to be Mac M1 compatible
> Added platform keys to docker-compose.yml

- apps/platform/db/migrations/20241119174518_add_journey_user_step_timestamp_index.js
Adds a missing composite key to `type` and `delay_until` columns
> Adds missing indexes to journey user step table

- apps/platform/src/users/User.ts
> Also allows rule matching on `external_id`

- apps/ui/src/ui/RRuleEditor.tsx
> Fixes year resetting in date inputs

- apps/platform/src/journey/JourneyController.ts
- apps/platform/src/journey/JourneyService.ts
- apps/platform/src/lists/ListController.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/rules/RuleService.ts
- apps/ui/src/api.ts
- apps/ui/src/views/journey/Journeys.tsx
- apps/ui/src/views/users/ListTable.tsx
> Adds duplication of lists and journeys

- apps/platform/src/lists/ListEvaluateUserJob.ts
- apps/platform/src/queue/Job.ts
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/ui/src/views/organization/Performance.tsx
Allows for execution of jobs at different priority levels
Fixes #583
> Adds priority jobs

- apps/ui/src/ui/utils.tsx
- apps/ui/src/views/campaign/CampaignPreview.tsx
- apps/ui/src/views/users/UserDetailAttrs.tsx
> Improves how user data is displayed when previewing campaign

- apps/ui/src/views/campaign/editor/EmailEditor.tsx
- apps/ui/src/views/journey/JourneyEditor.tsx
> Adds check for unsaved changes

- apps/platform/src/client/EventPostJob.ts
- apps/ui/public/locales/en.json
- apps/ui/public/locales/es.json
- apps/ui/src/ui/SearchTable.tsx
- apps/ui/src/views/organization/Performance.css
- apps/ui/src/views/organization/Performance.tsx
> Quality of life tweaks

- apps/platform/src/config/stats.ts
- apps/platform/src/organizations/OrganizationController.ts
- apps/platform/src/queue/Queue.ts
- apps/ui/public/locales/en.json
- apps/ui/public/locales/es.json
- apps/ui/src/api.ts
- apps/ui/src/views/organization/Performance.tsx
Adds a graph to show average timing for each job, will be helpful when debugging slow performance for folks
> Adds per-job timing metrics

- apps/platform/src/journey/JourneyStep.ts
> Fixes bug where journey link always takes 24hrs

- apps/platform/src/lists/ListService.ts
Most likely addresses #606 but waiting to hear back on details before merging
> When re-evaluating an existing list decrement count by removals

- apps/platform/src/journey/Journey.ts
- apps/platform/src/journey/JourneyController.ts
- apps/platform/src/journey/JourneyRepository.ts
- apps/platform/src/journey/JourneyService.ts
- apps/platform/src/journey/JourneyStep.ts
- apps/platform/src/journey/ScheduledEntranceOrchestratorJob.ts
- apps/ui/src/ui/RRuleEditor.tsx
- apps/ui/src/views/journey/steps/Entrance.tsx
> Allow for scheduling journey entrances by hour

- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/client/ClientController.ts
- apps/platform/src/core/validate.ts
> Adds AJV timezone validation to client API

- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/lists/ListService.ts
Switches to using a stream for fetching all users in a given list.
#624
> List regeneration performance improvements

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
Updates Github Action step versions to remove deprecated versions
> Updates Github actions to latest library versions

- apps/platform/src/providers/text/TelnyxTextProvider.ts
- apps/platform/src/providers/text/TextError.ts
- apps/platform/src/providers/text/TwilioTextProvider.ts
- Better logging for Twilio
- Correctly gets top error messages from Telnyx
> Improves error handling for SMS sending

- apps/platform/src/users/UserImport.ts
Ensures extra characters are stripped out and number comforts to e164 standard
> Improves parsing of phone numbers during user import

- apps/platform/src/config/queue.ts
- apps/platform/src/lists/List.ts
- apps/platform/src/lists/ListService.ts
- apps/platform/src/lists/UserListMatchJob.ts
- apps/platform/src/queue/RedisQueueProvider.ts
- apps/platform/src/users/UserImport.ts
- apps/platform/src/users/UserPatchJob.ts
- apps/platform/src/users/UserRepository.ts
- Stops greedily running code that isn't needed
- Reduces number of queries run during patch job
> Performance improvements for list import

- apps/platform/src/providers/text/TelnyxTextProvider.ts
Adds error code for trying to send to a number that the sending number doesn't support
> Adds handling for more region errors in Telnyx

- apps/platform/src/campaigns/CampaignGenerateListJob.ts
Fixes progress indicator for long running campaign generations
> Prevents campaign loading progress clobbering

- apps/platform/src/campaigns/CampaignService.ts
Tries going in another direction with generation. Pre-computing part of the list to speed things up
> Switches to temp tables for campaign generation

- apps/platform/src/campaigns/CampaignGenerateListJob.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/campaigns/CampaignStateJob.ts
- Increase lock length
- Start sending immediately
> Revert to original campaign generation implementation

- apps/platform/src/providers/text/TextJob.ts
- apps/platform/src/users/User.ts
- Better handles sending SMS messages to unsupported numbers
- Adds phone number metadata to users for better targeting
> Adds phone number metadata before insert

- apps/platform/src/lists/ListController.ts
- apps/platform/src/lists/ListEvaluateUserJob.ts
- apps/ui/public/locales/en.json
- apps/ui/public/locales/es.json
- apps/ui/public/locales/zh.json
- apps/ui/src/api.ts
- apps/ui/src/views/users/ListDetail.tsx
- Increases timeout for list regeneration
- Allows for list total count recalculation
> Allow list total recalculation

- apps/platform/src/config/env.ts
Previously values passed into Docker Compose were getting sent through as empty strings instead of undefined which was causing the default values to not get picked up when present in non-string types.
> Improves parsing of empty env values

- apps/platform/src/campaigns/Campaign.ts
- apps/platform/src/campaigns/CampaignService.ts
- apps/platform/src/journey/JourneyService.ts
- apps/ui/public/locales/en.json
- apps/ui/src/types.ts
- apps/ui/src/views/LoaderContextProvider.tsx
- apps/ui/src/views/campaign/CampaignOverview.tsx
- apps/ui/src/views/createStatefulRoute.tsx
- apps/ui/src/views/journey/JourneyEditor.tsx
Adds UI inside of campaign detail views to backlink to the journey that they are being used in
> Add UI to backlink to journeys from campaign

- apps/platform/src/providers/MessageTriggerService.ts
- apps/ui/src/ui/SearchTable.tsx
- apps/ui/src/ui/form/Select.css
- apps/ui/src/ui/form/SingleSelect.tsx
- apps/ui/src/views/campaign/Campaigns.tsx
Allows for filtering by blast or trigger type
> Add better campaign filtering
