apps/platform/src/render/TemplateController.ts, apps/platform/src/render/TemplateService.ts, apps/ui/src/api.ts, apps/ui/src/types.ts, apps/ui/src/views/campaign/CampaignPreview.tsx
Allow for sending proofs of email and sms templates to a given recipient. Super helpful for seeing how something will show up on the end device (especially emails)
=> Sending Template Proofs

apps/platform/src/config/env.ts, apps/platform/src/render/LinkController.ts, apps/platform/src/render/index.ts, apps/ui/docker/nginx/conf.d/default.conf, docs/docs/advanced/_category_.json, docs/docs/advanced/config.md, docs/docs/advanced/deeplinking.md
Deep links and universal links are rejected by apps if they don't have some files present in the `.well-known` folder. This allows a user to set a URL to proxy those files from
=> Allow for link wrapping deep links

apps/platform/package-lock.json, apps/platform/package.json, apps/platform/src/client/SegmentController.ts, apps/platform/src/config/env.ts, apps/platform/src/queue/Queue.ts, apps/platform/src/queue/QueueProvider.ts, apps/platform/src/queue/RedisQueueProvider.ts, apps/platform/src/queue/SQSQueueProvider.ts, docker-compose.yml, docs/docs/providers/segment.md
Adds Redis as an option for queues using BullMQ under the hood. The existing memory queue was pretty limiting as a "get started only with docker compose" option and adding Redis into that reduced memory usage overall but also allows for persistence across restarts
=> Add Redis queue option

apps/platform/src/utilities/index.ts
Segment 99% of the time always has a `-` in their locales, but sometimes one comes in without one strangely
=> Fixes locale parsing edge case

apps/platform/src/providers/email/Email.ts, apps/platform/src/render/Template.ts, apps/platform/src/render/TemplateController.ts, apps/ui/src/types.ts, apps/ui/src/ui/Preview.tsx, apps/ui/src/views/campaign/CampaignForm.tsx, apps/ui/src/views/campaign/EmailEditor.tsx, apps/ui/src/views/campaign/TemplateDetail.tsx
- Adds toast to templates
- Allows for a human readable name to be set for emails (to show up as a name in inboxes)
- Automatically generates a text copy of an email from HTML if none is provided
=> Adds from name and auto text email

apps/platform/db/migrations/20230419032608_users_allow_null_external_id.js, apps/platform/src/users/UserRepository.ts
Fixes an assumption that an external ID will always be present which is not true. A user can have just an anonymous ID value that can later be aliased (this is especially true of our mobile SDK)
=> Allow For NULL External ID

apps/platform/src/providers/email/SESEmailProvider.ts
SES oddly capitalizes certain fields for no apparent reason, this lowercases their header keys so we can appropriately match against them. This was preventing bounces, etc from being reported correctly
=> Fixes SES inbound notifications

apps/ui/package.json, apps/ui/src/views/campaign/editor/EmailEditor.tsx, apps/ui/src/views/campaign/editor/VisualEditor.tsx, package-lock.json, package.json
- run `npm run analyze:ui:bundle` to see dependency sizes
- lazy load `VisualEditor` because dependencies are quite large
=> adds bundle analyzer, shards visual editor

apps/platform/db/migrations/20230504131759_add_user_indexes.js, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/campaigns/__tests__/CampaignService.spec.ts, apps/ui/src/views/campaign/CampaignOverview.tsx, apps/ui/src/views/campaign/Campaigns.tsx
- Adds indexes to email and phone (completes PV-43)
- Fixes exclusion lists that weren't working (completes PV-42)
- Improves who campaigns are sent to (filtering out people without requisite values) (completes PV-41)
- Fixes initial list count not calculating properly because the math was wrong
=> Campaign sending improvements

apps/platform/src/render/TemplateService.ts
Currently link wrapping in email proofs is missing the email and campaign fields. This fixes that so that proofs have the full URL
=> Fixes template proof link wrapping

apps/platform/src/render/LinkController.ts
This PR moves base route to a 200 status instead of the original 302
=> Universal links require a 200 status for registered path

apps/platform/src/users/User.ts, apps/platform/src/users/UserRepository.ts, apps/ui/src/types.ts, apps/ui/src/views/users/UserDetailAttrs.tsx
Currently we assume a device is a model object. The way it's stored though is just as JSON inside of the models table. This means whenever devices are pulled, they don't have the instance method needed to determine if they can be sent. This PR moves to assuming a device is just an object. It also improves handling for some edge cases and improves the UI 
Completes PV-54
=> Fixes push notification sending

apps/platform/src/users/UserRepository.ts
MySQL has an issue where if a value is passed in a different type than a column the indexes dont appear to be fully used causing significantly worse performance
=> Forces string conversion to better use indexes

apps/platform/db/migrations/20230516214727_add_campaign_type.js, apps/platform/src/campaigns/Campaign.ts, apps/platform/src/campaigns/CampaignController.ts, apps/platform/src/campaigns/__tests__/CampaignService.spec.ts, apps/ui/src/types.ts, apps/ui/src/views/campaign/CampaignDetail.tsx, apps/ui/src/views/campaign/CampaignForm.tsx, apps/ui/src/views/campaign/CampaignOverview.tsx, apps/ui/src/views/journey/steps/Action.tsx
Add a campaign `type` field that can be either `blast` or `trigger`. This will allow for better segmenting campaigns associated with journeys and allow for better UI when updating.
blast = one time campaign
trigger = journey campaign
- Fixes a bug where you can "launch" a campaign created from a journey 
- Fixes bug where you can't edit a journey campaigns name without adding a list
=> Add campaign types

apps/platform/src/lists/ListService.ts, apps/platform/src/rules/WrapperRule.ts, apps/platform/src/rules/__test__/RuleEngine.spec.ts
This resolves two bugs related to user events triggering lists:
- If any list has logic that could cause the rule check to fail all subsequent checks end up being skipped
- Rule checking just for an event name doesn't work properly because it's defaulting to a user check vs event check
=> Event names are not causing lists to trigger

apps/platform/@types/knex.d.ts, apps/platform/src/auth/AdminRepository.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/config/database.ts, apps/platform/src/core/Model.ts, apps/platform/src/core/searchParams.ts, apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/projects/ProjectAdminRepository.ts, apps/platform/src/projects/ProjectService.ts, apps/platform/src/providers/ProviderService.ts, apps/platform/src/render/TemplateService.ts, apps/platform/src/storage/ImageController.ts, apps/platform/src/storage/ImageService.ts, apps/platform/src/subscriptions/SubscriptionService.ts, apps/platform/src/tags/TagController.ts, apps/platform/src/users/UserEventRepository.ts, apps/platform/src/users/UserRepository.ts, apps/platform/tsconfig.json, apps/ui/src/types.ts, apps/ui/src/ui/Pagination.tsx, apps/ui/src/ui/SearchTable.tsx, apps/ui/src/ui/Sidebar.tsx, apps/ui/src/views/campaign/CampaignForm.tsx, apps/ui/src/views/journey/steps/Action.tsx, apps/ui/src/views/journey/steps/Entrance.tsx, apps/ui/src/views/journey/steps/JourneyLink.tsx, apps/ui/src/views/settings/Teams.tsx, apps/ui/src/views/users/UserDetailEvents.tsx
Overall performance improvement as counting total number of results was getting quite slow for many views. This removes that need and switches entirely to cursor based paging with support for both going backwards and sorting.
- Removes counting total results when doing paging
- Adds `exact` and `partial` searching to improve performance for some views
- Allows for single column sorting of results and cursor paging backwards
Completes PV-12, PV-51
=> Improves paging by removing need for counting queries

apps/platform/src/campaigns/CampaignService.ts
Reduce the send pool by preemptively filtering users out before trying to send
=> Only send pushes to users with devices

apps/platform/src/auth/AuthMiddleware.ts, apps/platform/src/config/controllers.ts
Scoping was preventing secret API keys from ever working with private endpoints. Secret API keys should have roughly the same access as an admin would. Will need to introduce organization level permissions in the future.
=> Fixes problem preventing API keys from working

apps/platform/src/users/UserImport.ts, apps/platform/src/users/UserRepository.ts
MySQL does a terrible job at fully utilizing indexes when there is a type mismatch. If the external ID being provided by the client is a number, it wont be able to lookup the value fully utilizing the index. Currently the CSV parser will automatically cast external ID to a number if it interprets it as being one. This closes that loophole and also forces all comparisons to be string when performing a user lookup to avoid insert collisions in patch job
=> Forces casting to better utilize indexes

apps/platform/src/journey/JourneyRepository.ts, apps/ui/src/views/journey/JourneyEditor.tsx
- Fixes the reported total for each step
- Moves pending to only be a state for delay steps since all other steps operate instantly
=> Minor fixes to journey stats

apps/ui/src/ui/form/SchemaFields.tsx
Sets the type of a textfield to number when JSON schema needs it vs a string so that validation properly passes.
Fixes #213
=> Fixes schema fields not properly setting text inputs to numbers

apps/ui/src/views/campaign/CampaignDetail.tsx
When creating a new locale for non email campaigns it is failing because of allowing changing editor
=> Fixes empty locale creation

apps/platform/src/rules/RuleHelpers.ts, apps/platform/src/schema/UserSchemaService.ts, apps/platform/src/schema/__tests__/UserSchemaService.spec.ts
Currently reserved fields such as `created_at` are completely missing. This adds those fields
=> Adds reserved fields to rule schema fields

apps/platform/db/migrations/20230707221741_add_campaign_send_step_id.js, apps/platform/src/campaigns/Campaign.ts, apps/platform/src/campaigns/CampaignInteractJob.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/journey/JourneyService.ts, apps/platform/src/journey/JourneyStep.ts, apps/platform/src/providers/MessageTrigger.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/email/EmailJob.ts, apps/platform/src/providers/push/PushJob.ts, apps/platform/src/providers/text/TextJob.ts, apps/platform/src/providers/webhook/WebhookJob.ts, apps/platform/src/render/LinkService.ts, apps/platform/src/render/index.ts
1. added `campaign_sends.user_step_id`. this is now a part of its unique index so that we can send once per user step (including when the step is visited multiple times). this is not an actual FK because we need to allow `0` as a value for email blasts, since mysql doesn't work w/ `null` in the unique key.
2. action step type checks to see if the campaign has completed for that `campaign_id` + `user_id` + `user_step_id` combo before continuing. the reprocessing is triggered by the user event that is triggered by the send.
3. various other updates were needed to account for the new unique index on sends
=> Allows for recurring sends when a part of a journey

apps/platform/src/campaigns/CampaignGenerateListJob.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/utilities/index.ts
If a queue gets overloaded a campaign could continue regenerating and changing its state away from aborted, etc
=> Prevents campaign from regenerating list

apps/platform/src/rules/RuleHelpers.ts, apps/ui/src/views/users/RuleBuilder.tsx
The SQL generated for operators like `is set` was not correct and was generating fewer results than would be expected. This also updates the UI of the rule builder not now show the value field when one cant be set
=> Fixes rule matching for certain cases like 'is set'

apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/queue/Job.ts, apps/platform/src/queue/MemoryQueueProvider.ts, apps/platform/src/queue/Queue.ts, apps/platform/src/queue/QueueProvider.ts, apps/platform/src/queue/RedisQueueProvider.ts, apps/platform/src/queue/SQSQueueProvider.ts
Large throttled sends have a tendency to overload the queue to the point where it reaches unstable levels.
Causes:
- Items don't have their status updated until the queue updates it
- If an item is in the queue for longer than one minute (because of a large backlog), it'll be added (as a duplicate) again because the job to add sends to the queue re-runs
- If any of those added items then is throttled, it will duplicate itself keeping the queue at its inflated size for longer than necessary
This PR prevents duplicate jobs by manually setting the ID and also improves the delay process for jobs running in Redis queues.
=> Improves how campaign sends are added to the queue

apps/platform/db/migrations/20230827174518_add_user_events_date_index.js, apps/platform/src/schema/UserSchemaService.ts
- Adds `created_at` index to `user_events`
- Adds `updated_at` index to `users`
Should overall improve performance of all schema lookups and improve general performance of other queries as a result
=> Improves lookups for schema changes by adding indexes

apps/platform/db/migrations/20230828003728_add_user_list_index.js, apps/platform/src/config/redis.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/lists/ListStatsJob.ts, apps/platform/src/lists/__tests__/ListStatsJob.spec.ts, apps/platform/src/providers/Provider.ts
Adds caching to user list counting so values don't have to be completely recalculated every time
=> Improves performance of list total counting

apps/platform/db/migrations/20231008171139_update_admin_invite.js, apps/platform/src/projects/ProjectAdminController.ts, apps/ui/src/api.ts, apps/ui/src/types.ts, apps/ui/src/ui/Button.tsx, apps/ui/src/views/settings/TeamInvite.tsx, apps/ui/src/views/settings/Teams.tsx
- Allows for adding people to a project that have not used Parcelvoy before
=> Improves project invite flow

apps/ui/src/ui/SourceEditor.css, apps/ui/src/ui/SourceEditor.tsx, apps/ui/src/variables.css, apps/ui/src/views/campaign/CampaignPreview.css, apps/ui/src/views/campaign/CampaignPreview.tsx, apps/ui/src/views/campaign/editor/EmailEditor.css, apps/ui/src/views/campaign/editor/HtmlEditor.tsx, apps/ui/src/views/journey/steps/Update.tsx, apps/ui/src/views/project/ProjectSidebar.tsx
- Wraps source editor to ensure consistent styling and experience
- Prevents crashes from malformed json
=> Improves styling of source editor and crashes

apps/platform/src/lists/ListService.ts, apps/platform/src/rules/RuleService.ts
- Fixes `Column 'project_id' in where clause is ambiguous` error
- Fixes rule evaluations occasionally having duplicates when processed in quick succession or in certain rules
=> Fixes rule evaluation and list errors

apps/platform/src/lists/ListService.ts, apps/ui/src/views/users/RuleBuilder.tsx
- Only insert children if they exist
- Don't populate on empty list creation, only on updates
- Fixes UI around newly created lists
=> Fixes list creation

apps/platform/src/organizations/OrganizationService.ts, apps/ui/src/views/organization/Admins.tsx
Prevents username overlap from happening at creation time if someone has picked one that exists already
=> Minor fixes to org creation

apps/platform/src/utilities/index.ts
Fixes chunk method not properly awaiting which was causing jobs that use the chunking method to frequently timeout and stall.
=> Fixes chunk method not properly awaiting

README.md, apps/platform/src/campaigns/CampaignGenerateListJob.ts, apps/platform/src/campaigns/CampaignSendJob.ts, apps/platform/src/journey/ScheduledEntranceJob.ts, apps/platform/src/journey/ScheduledEntranceOrchestratorJob.ts
Long running processes were overlapping if they took longer to processes than how often they are scheduled. This PR adds a lock to ensure each job is only running once
=> Adds locks to long running campaign processes

apps/ui/src/views/campaign/TemplateDetail.tsx
Previously it was a bit murky how many segments were actually going to be sent and how SMS segments worked. This PR splits the statistics into two groups showing how many segments would be used for new users and how many for existing. It also calls out that sending slows down the more segments you are trying to send.
=> Improves information about SMS send

apps/ui/src/views/router.tsx
Instead of always sending you to the project selector at login, you are now sent to the last project you were modifying if there is one. You can still use the project selector in the top left to switch between
=> Auto redirects to last project after login

apps/platform/src/lists/ListService.ts
Currently for event only lists the wrapper rule can sometimes also be applied which can lead to false negatives. This ensures that the wrapper rule is never applied during evaluation.
Fixes #316
=> Fixes how rules are applied to event only lists

apps/platform/src/lists/List.ts, apps/platform/src/lists/ListController.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/lists/__tests__/ListService.spec.ts, apps/ui/src/types.ts, apps/ui/src/views/users/ListCreateForm.tsx, apps/ui/src/views/users/ListDetail.tsx, apps/ui/src/views/users/ListTable.tsx
Dynamic lists currently begin to populate immediately after creation which can be problematic since a list in its creation state wont have any rules yet. This adds a draft state to lists which they are in by default. Client events wont check the list when evaluating so no users should join the list until it goes into a published state.
=> Adds a draft/publish state for lists

apps/platform/src/lists/ProcessListsJob.ts, apps/ui/src/views/users/ListDetail.tsx
Running list stats can cause issues while records are still being imported. Only calculate statistics for lists that have finished initial generation.
Also hides count while import is running.
=> Prevent list stats during list generation

docs/docusaurus.config.js
Switches documentation to live under the primary domain instead of on a subdomain
=> Switches documentation URL

apps/platform/src/config/env.ts, apps/platform/src/storage/ImageController.ts, apps/platform/src/storage/S3StorageProvider.ts, apps/platform/src/storage/Storage.ts, apps/ui/src/ui/form/UploadField.tsx, apps/ui/src/views/campaign/ImageGalleryModal.tsx, docs/docs/advanced/config.md, docs/docs/advanced/storage.md
Adds the `endpoint` field to the configuration allowed by the S3 storage method to allow for other S3-compatible clients to be used addressing the request in #337
Also adds docs and improves the upload process
=> Allows for using alternate S3 providers

apps/platform/src/journey/JourneyService.ts, apps/platform/src/journey/__tests__/JourneyService.spec.ts
Fixes regression caused by #330 where new journeys created since that merge were not being appropriately picked up by the journey scheduler.
Updates test case to ensure its covered moving forward
Fixes #336
=> Fixes regression that broke new event based journey entrances

apps/platform/src/journey/JourneyStep.ts
Properly flattens events before sending them to gates so that data parameters can be accessed without the `data` key in the path.
Fixes #344
=> Fixes bug where events for gates where not flattened

apps/platform/src/render/index.ts
Like in other journey steps like User Update, the campaign action now allows for accessing journey data via the `journey` key. To access event data from a given step for example, a given campaign template would access `{{ journey.step_data_key.event.param }}`
=> Allows for accessing journey data from campaign

apps/platform/src/campaigns/Campaign.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/text/TextJob.ts
- If a text send fails, prevents the status from getting overridden
- Doesn't let a campaign send re-run or avoid its lock if it had previously failed
=> Addresses some edge cases when a text send fails or is aborted

apps/platform/src/campaigns/CampaignGenerateListJob.ts, apps/platform/src/campaigns/CampaignService.ts
- Switches how the query to generate the list of users for a campaign is structured. On average is 10% faster, but also returns records 10x faster leading to what feels like a much snappier experience since users are visible in the UI quite quickly.
- Uses an estimate of the number of records the generation will be calculating over to determine the lock time for the query
=> Improves campaign generation performance

apps/platform/src/subscriptions/Subscription.ts, apps/platform/src/subscriptions/SubscriptionController.ts, apps/platform/src/subscriptions/SubscriptionService.ts, apps/ui/src/api.ts, apps/ui/src/types.ts, apps/ui/src/views/settings/Subscriptions.tsx
In settings the subscription screen had a link where instead it should've been a static table. This instead updates that table to allow for at least editing the subscription name. The channel type cannot be changed after creation.
Fixes #371
=> Fixes broken link when clicking on a subscription

apps/platform/src/auth/AuthProvider.ts
Fixes regression introduced in 1.3.5 where the first user in a new organization would not have the proper permissions to create projects. The first user should always be an owner.
=> First member of an organization should be owner

apps/platform/db/migrations/20240323145423_add_journey_step_child_key.js, apps/platform/src/journey/JourneyController.ts, apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/journey/JourneyStep.ts, apps/platform/src/journey/__tests__/JourneyService.spec.ts, apps/ui/src/types.ts, apps/ui/src/views/journey/JourneyEditor.tsx, apps/ui/src/views/journey/steps/Balancer.tsx, apps/ui/src/views/journey/steps/Experiment.tsx, apps/ui/src/views/journey/steps/Gate.tsx
- adds `journey_step_child.path` field for key/group/handle name (e.g. "yes", "no" for gates)
- updated tests and UI accordingly
=> Added step child path field for explicit grouping

apps/platform/src/providers/analytics/AnalyticsProvider.ts, apps/platform/src/providers/analytics/SegmentProvider.ts, apps/platform/src/users/UserEventRepository.ts, apps/platform/src/users/UserRepository.ts
Currently only the external ID is passed but a user can be created without one which can cause an event to be triggered with no user association
=> Ensures the anonymous ID is passed along to analytics

apps/platform/src/journey/JourneyController.ts, apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/users/UserController.ts, apps/platform/src/users/UserRepository.ts, apps/ui/src/types.ts, apps/ui/src/views/journey/EntranceDetails.tsx, apps/ui/src/views/journey/JourneyEditor.tsx, apps/ui/src/views/users/UserDetailJourneys.tsx
- Adds API endpoint for exiting a user from a journey `DELETE /api/client/journeys/:journeyId/users/:externalUserId`
- Moves user endpoints to allow for passing in external ID instead of internal IDs
- Minor UI fixes
Partially addresses #407
=> Allows for exiting a journey via API

apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/core/searchParams.ts, apps/ui/src/types.ts, apps/ui/src/views/journey/steps/Action.tsx
Currently duplicating a campaign moves it to a draft state, but you cant launch a triggered campaign as it should always be running. This fixes that issue and also prevents you from selecting non-triggered campaigns inside of journeys since they may not work properly.
Fixes #417
=> Fixes duplicating journey "triggered" campaigns

apps/platform/src/users/User.ts, apps/platform/src/users/UserImport.ts, apps/platform/src/users/UserPatchJob.ts, apps/platform/src/users/UserRepository.ts, apps/ui/src/types.ts, apps/ui/src/views/users/UserDetailAttrs.tsx, docs/docs/how-to/lists.md
When creating a static list, you can now pass in a `created_at` field which will override the default setting of that field for users created allowing you to set it to times in the past. This field accepts a string ISO 8601 date.
Fixes #416
=> Allows for uploading user created at dates statically

apps/platform/src/auth/BasicAuthProvider.ts
Basic auth had some extra superfluous logic that was preventing the organization creation and role permissioning from running properly. This fixes the issue that if you are setting up Parcelvoy for the first time using basic auth you wont have access to manage the organization or projects. This issue does not affect any other authentication method.
Fixes #415 and #399
=> Fixes org & role onboarding setup for basic auth

apps/platform/src/render/LinkService.ts
Prevents internal links from being excluded from link wrapping for click tracking purposes
=> Wraps all links even internal ones for click tracking

apps/platform/db/migrations/20240315211220_add_reference_to_campaign_send.js, apps/platform/src/journey/JourneyStep.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/webhook/WebhookJob.ts, apps/ui/public/locales/en.json, apps/ui/public/locales/es.json
For campaign sends associated with journey steps, if a given step where to fail the journey would not be notified causing that users journey to stall out. This addresses that issue and also cleans up a bit of other journey/campaign interaction code.
=> Fixes loophole where a failed send would cause a journey to stall

apps/platform/src/lists/ListService.ts, apps/platform/src/lists/ListStatsJob.ts, apps/platform/src/users/UserImport.ts
The timestamp field on the `user_list` table didn't have enough precision to accurately handle segmented counting. This adds the identifier as a field to further enhance the range that is being counted
=> Improves precision of list total counting

apps/platform/src/render/LinkService.ts, apps/platform/src/render/index.ts, docs/docs/how-to/campaigns/templates.md, docs/docs/how-to/settings/subscriptions.md
Previously if you had link wrapping enabled you would have to use `{{{ unsubscribeEmailUrl }}}` (triple bracket) to get to the URL since it would have tags that should not be escaped. This was not called out anywhere and could definitely be problematic so this PR resolves and problem and improves documentation.
Also improves what elements are click wrapped.
Fixes #440
=> Move unsubscribe URLs to be safe links to prevent escaping

apps/platform/src/journey/JourneyStep.ts, apps/platform/src/journey/ScheduledEntranceOrchestratorJob.ts, apps/ui/src/ui/RRuleEditor.tsx, apps/ui/src/ui/form/RadioInput.css, apps/ui/src/views/journey/steps/Entrance.tsx
Improves scheduling users to enter a journey by allowing for a single time schedule instead of just a recurring schedule.
=> Allow scheduling journey sends once

apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/lists/ListService.ts, apps/ui/src/views/users/ListDetail.tsx
Tags wouldn't reflect as set in the UI until after the page was reloaded since the response from the patch request wasn't including the relationship properly
Fixes #452
=> Fixes tags not showing until page reload

apps/platform/db/migrations/20240419015246_add_project_text_help.js, apps/platform/src/journey/JourneyStep.ts, apps/platform/src/projects/Project.ts, apps/platform/src/projects/ProjectController.ts, apps/platform/src/providers/text/HttpSMSProvider.ts, apps/platform/src/providers/text/NexmoTextProvider.ts, apps/platform/src/providers/text/PlivoTextProvider.ts, apps/platform/src/providers/text/TextProvider.ts, apps/platform/src/providers/text/TwilioTextProvider.ts, apps/platform/src/subscriptions/SubscriptionController.ts, apps/platform/src/subscriptions/SubscriptionService.ts, apps/ui/public/locales/en.json, apps/ui/src/types.ts, apps/ui/src/ui/CodeExample.tsx, apps/ui/src/views/project/ProjectForm.tsx, docs/docs/providers/twilio.md
- Allows for triggering journeys based on inbound SMS. Inbound messages will create an event `text_inbound` containing the message that can be used to run logic on
- Adds pre-built help functionality required by SMS short codes
=> Adds better support for inbound SMS

apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/journey/ScheduledEntranceOrchestratorJob.ts, apps/ui/src/ui/RRuleEditor.tsx, apps/ui/src/views/journey/steps/Entrance.tsx
- Scheduled journey entrances enforce single entrance
- Ensures that saving a journey doesn't reset the next occurrence if the schedule field hasn't changed
=> Better enforces single run journey entrances

apps/platform/package-lock.json, apps/platform/package.json, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/providers/push/LocalPushProvider.ts, apps/ui/public/locales/en.json, apps/ui/public/locales/es.json, apps/ui/src/types.ts, apps/ui/src/views/campaign/LaunchCampaign.tsx, apps/ui/src/views/campaign/TemplateDetail.tsx
Google has deprecated their original GCM endpoints for sending notifications. These had been migrated into Firebase and were largely considered to be the FCM way of sending notifications. However, Google is now requiring people to use their next version of FCM endpoints and is shutting off servers this month for the old ones.
This PR also addresses some campaign logic issues around sending push notifications.
=> Switches to latest FCM APIs

apps/platform/src/queue/SQSQueueProvider.ts
This fixes the Message SQS Queue Provider. "DelaySeconds" was being sent in milliseconds, however AWS SQS accepts seconds (and 900 is the maximum).
Screenshot of the error from worker below:
=> Fixes Message SQS DelaySeconds

apps/platform/db/migrations/20240808205738_add_provider_rate_interval.js, apps/platform/src/campaigns/__tests__/CampaignService.spec.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/Provider.ts, apps/ui/public/locales/en.json, apps/ui/public/locales/es.json, apps/ui/src/types.ts, apps/ui/src/views/settings/IntegrationModal.tsx
This implements a rate interval when creating a Provider. Before the interval was fixed at 'second' rate and the slowest rate was 1 per second.
With this PR, it is possible to send campaigns on 1 per minute rate, 1 per hour, etc.
I've tested on 1 per minute and 1 per hour, both worked flawlessly.
=> Added rate interval on provider

apps/platform/src/providers/email/Email.ts, apps/platform/src/providers/email/EmailChannel.ts, apps/platform/src/providers/email/EmailProvider.ts, apps/platform/src/render/index.ts, apps/platform/src/subscriptions/SubscriptionController.ts
=> Add email unsubscribe header

apps/platform/src/client/SegmentController.ts
Fixes a bug that could occur when calling identify in the Segment controller where traits would be null
=> Allows for Segment traits to be null

apps/platform/src/users/User.ts
For situations where the dataset has a variable with the full name value, default to that instead
=> Better handle if dataset has a fullname value

apps/platform/src/auth/GoogleAuthProvider.ts, apps/platform/src/auth/OpenIDAuthProvider.ts, apps/platform/src/config/env.ts, docs/docs/advanced/authentication.md
Currently only `id_token` is supported, based on feedback in #487, this set of changes allows for passing in custom types based on what the OpenID provider supports.
=> Allows for additional OpenID response types

apps/platform/src/client/EventPostJob.ts, apps/platform/src/subscriptions/SubscriptionService.ts, apps/platform/src/users/UserRepository.ts
Subscription status events were never updated to trigger journey logic after we updated journey entrance types. This brings them in line with how we handle `user_created` events
Fixes #512
=> Have subscription status events trigger journeys

apps/platform/src/organizations/OrganizationMiddleware.ts, apps/platform/src/providers/push/PushJob.ts, apps/ui/docker/nginx/conf.d/default.conf
Fixes passthrough of universal link endpoints for iOS and Android under certain conditions
=> Tweak proxy for universal link registration

apps/ui/public/locales/en.json, apps/ui/public/locales/es.json, apps/ui/src/ui/DataTable.css, apps/ui/src/ui/DataTable.tsx, apps/ui/src/views/campaign/Campaigns.tsx
- Move to single column for engagement to better cover channel types
- Increase information density by dropping seconds from fields that dont need them
=> Condense data on campaigns list

apps/platform/db/migrations/20241017002221_reset_list_totals.js, apps/platform/src/config/redis.ts, apps/platform/src/lists/ListPopulateJob.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/lists/ListStatsJob.ts, apps/platform/src/lists/__tests__/ListService.spec.ts
Currently the list count has a fundamental flaw in that its not decrementing the total whenever a user is removed from a list so over time it just continues to drift upward.
This completely removes partial counting from the list totals equation and instead relies on redis key incrementing and decrementing to keep track of totals and then periodically pulls those values into the database. This removes the counting load almost completely from the database.
It also fixes re-counting when updating a ruleset for a list.
This does temporarily reset the count of every list to zero so that they can be recalculated accurate to start the new incrementing system.
=> Fixes list count drifting over time

apps/platform/src/campaigns/Campaign.ts, apps/platform/src/campaigns/CampaignService.ts
It seems like some browsers aren't properly formatting dates such that the DB isn't happy, this forces the `send_at` date for campaigns to be parsed as a JS date before insertion into the DB
=> Force casting of send at value

apps/platform/src/campaigns/Campaign.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/campaigns/__tests__/CampaignService.spec.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/providers/Provider.ts
Currently after you create a campaign it does not update the user the list will be going to even if you schedule the campaign for way in the future. The initial rationale behind this is that generating a send is expensive and it's hard to know when to cutoff a list since you could be sending to a disparate group of timezones.
This logic piggybacks off of the performance improvements introduced by rule caching to check for list additions and removals to know if we should re-check a users enrollment in a campaign. If the campaign has not yet started running and a users enrollment changes, we want to reflect that in the campaign by either adding or removing the user from the send. This should at best get you granularity up until the minute before a send and at worst up to 24hrs off depending …
=> Adds logic to perpetually keep a send list up to date

docker-compose.yml
The `healthcheck.start_period` attribute was introduced in Docker Compose 3.4
=> Correct required docker compose version

apps/platform/src/campaigns/CampaignEnqueueSendsJob.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/campaigns/__tests__/CampaignService.spec.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/Provider.ts, apps/platform/src/queue/MemoryQueueProvider.ts
- Reduce Redis memory usage by only enqueuing the most jobs that are possible over a given rate limit
- Allow for recovery of throttled jobs in the case of Redis running out of memory by re-adding them to the queue just like pending jobs
=> Improve campaign send performance

apps/platform/db/migrations/20241109235323_add_list_refreshed_at.js, apps/platform/db/migrations/20241119174518_add_journey_user_step_timestamp_index.js, apps/platform/src/config/queue.ts, apps/platform/src/journey/JourneyRepository.ts, apps/platform/src/lists/List.ts, apps/platform/src/lists/ListController.ts, apps/platform/src/lists/ListRefreshJob.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/lists/ProcessListsJob.ts, apps/platform/src/rules/DateRule.ts, apps/platform/src/rules/RuleError.ts, apps/platform/src/rules/RuleHelpers.ts, apps/platform/src/rules/RuleService.ts, apps/platform/src/users/UserRepository.ts, apps/ui/src/views/users/ListDetail.tsx, apps/ui/src/views/users/RuleBuilder.css, docs/docs/how-to/lists.md
First pass at allowing for daily regeneration of lists that include relative date math in them. This solution is relatively efficient for date math that compares forwards (or looks for dates greater than the generated value) but very inefficient for date math comparing backwards. This is because backwards comparison typically opens the criteria for membership in a list to a greater population requiring re-evaluating all users in a given project (not just looking at those already in the list). Depending on user base size this can take a solid amount of time. 
Will continue investigating how to improve situations involving backwards looking relative dates, but most described use cases look forward to limit membership for only a defined criteria before removing users already in the list (vs …
=> Automatic List Regeneration When Using Relative Date Rules

apps/platform/src/providers/push/LocalPushProvider.ts, apps/platform/src/providers/push/LoggerPushProvider.ts, apps/platform/src/providers/push/Push.ts, apps/platform/src/providers/push/PushChannel.ts, apps/platform/src/providers/push/PushJob.ts
Currently if a user has multiple devices and one of them has an invalid token we fail the entire send (even though some of them were unsuccessful). This updates the behavior to not consider a push notification send as a failure unless 100% of the sends were unsuccessful. 
Fixes #546
=> Better handle users with multiple devices and devices with expired tokens

apps/platform/src/campaigns/CampaignEnqueueSendsJob.ts, apps/platform/src/campaigns/CampaignService.ts
- Reduces how often it runs by only running if a campaign has been sending for longer than the check delta. 
- Reduces deadlocks by reading records and then marking by ID instead of doing update in the DB
Related to #541
=> Improve logic for stalled sends

apps/platform/src/render/Template.ts
In our workflows, we want to send custom deeplinks to users based on some of their attributes. For this to work, we need to have handlebars interpretation for URLs.
This PR does just that by calling the `Render` method on the URL before wrapping it.
=> feature: Allow handlebars usage in PushTemplate

apps/platform/src/render/Template.ts
Follow-up to #568 where I found there was an issue regarding `undefined` url (mea culpa).
This PR handles the case where no deeplinks are specified to a `PushTemplate`.
=> Fixed Url rendering in PushTemplate to support undefined value

apps/platform/src/config/queue.ts, apps/platform/src/config/redis.ts, apps/platform/src/lists/List.ts, apps/platform/src/lists/ListController.ts, apps/platform/src/lists/ListEvaluateUserJob.ts, apps/platform/src/lists/ListPopulateJob.ts, apps/platform/src/lists/ListService.ts, apps/platform/src/lists/ListStatsJob.ts, apps/platform/src/lists/__tests__/ListService.spec.ts, apps/platform/src/queue/Queue.ts, apps/platform/src/rules/RuleService.ts, apps/ui/src/types.ts, apps/ui/src/views/users/ListDetail.tsx, apps/ui/src/views/users/ListTable.tsx
- Speeds up fetching of data by using a stream instead of a scroll
- Moves to distributed processing of records to allow for horizontal scaling
- Adds progress indicator for how far along a list is in its original generation
- Doesn't update list update at timestamp on user count change
=> Allows for distributed list generation

apps/platform/src/providers/text/TelnyxTextProvider.ts, apps/platform/src/providers/text/TextProvider.ts, apps/platform/src/providers/text/index.ts, apps/platform/src/subscriptions/SubscriptionService.ts, docs/docs/providers/telnyx.md, docs/docs/providers/twilio.md
- Allows for resubscribing to the SMS channel by sending the keyword `START`
- Adds a provider for sending SMS via Telnyx
=> Adds Telnyx SMS provider, enables SMS resubscribe

apps/ui/package-lock.json, apps/ui/package.json, apps/ui/public/locales/en.json, apps/ui/public/locales/es.json, apps/ui/src/views/users/ListDetail.tsx, apps/ui/src/views/users/RuleBuilder.tsx, package-lock.json
- Adds check for unsaved changes
- Adds loading indicator when generating list
=> Improve list detail UI

apps/platform/src/queue/Job.ts, apps/platform/src/queue/RedisQueueProvider.ts, apps/platform/src/users/UserDeviceJob.ts
Currently if there are timing issues or a user is deleted but a device request comes in subsequently it will error out when in reality it should just stop retrying since there isn't an action that can be taken.
=> Don't error our device saving for nonexistent user

apps/platform/src/campaigns/CampaignInteractJob.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/campaigns/CampaignStateJob.ts
=> Selectively refresh stats for opened campaigns

apps/platform/src/lists/ListService.ts, apps/platform/src/rules/Rule.ts, apps/platform/src/rules/StringRule.ts, apps/ui/src/types.ts, apps/ui/src/views/users/RuleBuilder.tsx
Also fixes user name list issue
Fixes #593
=> Adds new inverse rule operators

apps/platform/db/migrations/20241228214210_modify_journey_user_step_indexes.js, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/lists/ListEvaluateUserJob.ts, apps/platform/src/utilities/index.ts
Simple change to potentially reduce gap locks by not having to re-select records for update
=> Exploration to reduce deadlocks

apps/platform/src/campaigns/Campaign.ts, apps/platform/src/utilities/index.ts, docs/docs/api/client.md, docs/docs/how-to/lists.md
This is most likely a temporary code change only as I am unsure as to the performance implications of it all. But at the very least it also highlights even more the required formats in the documentation
=> Force timezone check during record creation

apps/platform/src/providers/text/TelnyxTextProvider.ts
Apparently error codes are numbers vs strings causing certain cases to not be caught
=> Fixes assuming Telnyx error codes are numbers

apps/platform/db/migrations/20250307055453_update_campaign_send_primary_keys.js, apps/platform/package.json, apps/platform/src/campaigns/Campaign.ts, apps/platform/src/campaigns/CampaignEnqueueSendsJob.ts, apps/platform/src/campaigns/CampaignInteractJob.ts, apps/platform/src/campaigns/CampaignService.ts, apps/platform/src/campaigns/CampaignStateJob.ts, apps/platform/src/core/Model.ts, apps/platform/src/core/searchParams.ts, apps/platform/src/journey/JourneyStep.ts, apps/platform/src/providers/MessageTrigger.ts, apps/platform/src/providers/MessageTriggerService.ts, apps/platform/src/providers/email/LoggerEmailProvider.ts
- Switches to composite primary key vs auto-incrementing to reduce range locking
- Increased number of campaigns inserted by 10x (produces an inline speed increase in campaign initialization)
- Removed `on duplicate merge` insert logic to prevent deadlocks while inserting records
=> Campaign list generation performance improvements

docs/docs/advanced/authentication.md
`AUTH_DRIVER` in docs for configuring SAML authentication in Google Workspace is `basic` in stead of `saml`.
=> fix(docs): incorrect auth_driver in Google workspace SAML instructions

apps/platform/src/error/SentryProvider.ts, apps/platform/src/providers/MessageTriggerService.ts
Adds contextual data to send failures that bubble up to error tracker. Also makes sure Sentry gets `extra` data
Resolves #666
=> Adds additional context to send errors tracked in Sentry/Bugsnag
